[package]
name = "shopify_api"
description = "Shopify API client"
documentation = "https://docs.rs/shopify_api"
readme = "README.md"
repository = "https://github.com/0xtlt/shopify_api"
version = "0.2.1"
edition = "2021"
keywords = ["shopify", "api", "client"]
categories = ["api-bindings", "web-programming"]
license = "MIT"
authors = ["Thomas Tastet"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json"] }
serde_json = { version = "1", default-features = false }
serde = { version = "1", default-features = false, features = ["derive"] }
chrono = "0.4"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[features]
default = ["rustls"]
rustls = ["reqwest/rustls-tls"]
native-tls = ["reqwest/native-tls"]